# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: nanoc-bibtex 1.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "nanoc-bibtex".freeze
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Ruben Verborgh".freeze]
  s.date = "2020-09-17"
  s.description = "BibTeX data source for nanoc.".freeze
  s.email = "ruben@verborgh.org".freeze
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/nanoc/data_sources/bibtex_data_source.rb",
    "nanoc-bibtex.gemspec"
  ]
  s.homepage = "http://github.com/RubenVerborgh/nanoc-bibtex".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.1.2".freeze
  s.summary = "BibTeX data source for nanoc.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<nanoc>.freeze, ["~> 4.2"])
    s.add_runtime_dependency(%q<bibtex-ruby>.freeze, ["~> 5.1"])
    s.add_runtime_dependency(%q<latex-decode>.freeze, ["~> 0.2"])
    s.add_development_dependency(%q<bundler>.freeze, ["~> 2.0"])
    s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.0"])
  else
    s.add_dependency(%q<nanoc>.freeze, ["~> 4.2"])
    s.add_dependency(%q<bibtex-ruby>.freeze, ["~> 5.1"])
    s.add_dependency(%q<latex-decode>.freeze, ["~> 0.2"])
    s.add_dependency(%q<bundler>.freeze, ["~> 2.0"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.0"])
  end
end

